### ISSUE TITLE
While performing Incremental training for ASR should not we re-train tokenizer and LM models as well?

### ISSUE THREAD

**Issue by yilmazay74** [shahad-mahmud/incremental_learning_for_asr#3]
First of all thanks for creating this incremental asr repo, we were just looking for such a functionality.
Here it seems to me that something has been forgotten or ignored.
In the readme it describes the incremental ASR as if the tokenizer and the LM is not being re-trained.
And looks like it is assumed that the previous tokenizer and LM models are used.
Namely while doing the second task for incremental asr training, normally I would expect to start from re-training tokenizer first, 
and then the LM and finally the ASR model. 
Am I wrong? Or is it really the fact that the tokenizer and LM models do not make much difference, 
so we can use the previous tokenizer and LM models for training the second (new ASR) task?
If someone could explain that, I would be very glad.
( this incremental training feature is very crucial for our ASR models.)

Best Regards
Thanks in advance.

**Comment by yilmazay74** [comment]
By the way, if I expected, if the tokenizer and LM models need re-training incrementally as well, 
could you please update Readme so that it explains how to do that step by step?
Any response or guidance will be very much appreciated.
Thanks again.

**Comment by shahad-mahmud** [comment]
First of all, we will not want to re-train the tokenizer. Because, if we do so, the prediction space will be changed for the parent model, which is not expected. 

If you trained the tokenizer on a large and diverse text corpus, then we would expect that it already contains well structured tokens. Thus not needed to train again for the new text data.

In this repository, I've used an end-to-end ASR model without integrating any external LM. So you don't have to worry about the LM. However, if you plan on using an external LM in the shallow fusion method, then you can train the LM separately at any time. Since it's trained externally with different objectives, like MLM and NSP for BERT, it can be easily fused with the ASR model in a shallow manner.

I hope this clears things up for you! Let me know if you have any other questions.

**Comment by yilmazay74** [comment]
Thanks a lot. That was so much appreciated.
